In [1]:
import numpy as np

my_list = list(range(1000000))
my_array = np.arange(1000000)

In [2]:
my_list2 = [i * 2 for i in my_list]
# list comprehension 으로 my_list 안의 숫자 리스트 안의 모든 숫자들을 곱하기 2 하는 방법

my_array = my_array * 2
#numpy 라이브러리로는 이렇게 간단하게 곱하기 2

In [3]:
%timeit my_list2 = [i * 2 for i in my_list]
%timeit my_array2 = my_array * 2
# %timeit 이라는 명령어를 통해, 이 연산을 처리하는데 얼마 만큼의 시간이 걸리는 지를 측정할 수 있음.
# numpy 를 왜 써야 하는 지를 알려줌! 숫자 배열에 특화되어있다. 

41.4 ms ± 10.6 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
2.66 ms ± 204 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [4]:
#2차원 형태 (;리스트 안의 리스트)의 a 라는 리스트를 생성
a = [
    [1, 1.2, 3],
    [-123, 123, 0]
]
data = np.array(a)
print(data)
# 일괄적으로 (넓은 범위의 데이터로) 형태가 맞춰진 상태 - 소수로

[[   1.     1.2    3. ]
 [-123.   123.     0. ]]


In [5]:
#np 는 연산이 꽤나 편하다. 

In [6]:
print(data * 10)
# 곱셈 연산을 할 때, 각각 하나의 데이터에 곱셈을 바로 해준다. 
# 각각 아이템으로 곱셈 연산을 하게된다. 
# python 에서는 list 를 통해 반복되는데

# 0차원 : 스칼라 (scala), 1차원 : 백터 (vector), 2차원 : 행렬 (matrix), 3차원 : 텐서 (tenser)
# scala : 단일 요소의 데이터에 대한 곱셈 연산 이라고 생각하자. 
# 파이썬 기본 문법과는 연산이 다르게 적용된다. 

print(data + data)
# 덧셈도 마찬가지

[[   10.    12.    30.]
 [-1230.  1230.     0.]]
[[   2.     2.4    6. ]
 [-246.   246.     0. ]]


In [7]:
print(data.shape)
# 가장 큰 단위의 배열의 개수를 출력 - 배열 안의 배열 안의 배열, ...
print(data.dtype)
# 데이터의 세부 타입
# float; 실수

(2, 3)
float64


## ndarry 생성하기

In [8]:
data1 = [1, 2, 3, 4, 5]
arr1 = np.array(data1)
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [9]:
arr2 = np.array([[1.1, 2.2], [3.3, 4.4]])
print(arr2)
print(type(arr2))

[[1.1 2.2]
 [3.3 4.4]]
<class 'numpy.ndarray'>


In [10]:
print(arr1.ndim)
print(arr2.ndim)
#배열의 차원수를 알려주는 명령어 .ndim

1
2


In [11]:
print(arr1.shape)
print(arr2.shape)

(5,)
(2, 2)


In [12]:
## 이부분 뭔가 이상한 거 같아 git 보고 수정하기!!

print(np.zeros(10))
print([0] * 10)
# 숫자 리스트에서는 두번째 방법으로 리스트를 만들었던 것과 동일한 방법임
print(np.zeros(   (5, 5)  ))
print(np.empty((2, 2, 2)))
# 메모리 상의 아무값 - 난수가 들어간 리스트가 생성됨. 

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [13]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


## ndarray 자료형

In [14]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
#생성 할 때, 형을 지정해서 생성하도록 명령하는 것
print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [15]:
arr1 = np.array([1, 2, 3])
print(arr1.dtype)
#명시적으로 형변환을 하려면 원래 int64 에서 => 
float_arr1 = arr1.astype(np.float64)
print(float_arr1)
print(float_arr1.dtype)

int64
[1. 2. 3.]
float64


In [16]:
arr2 = np.array([1.1, 2.2, 3.3, 9.9])
print(arr2.dtype)
int_arr2 = arr2.astype(np.int64)
print(int_arr2)
print(int_arr2.dtype)

float64
[1 2 3 9]
int64


## 산술 연산

In [17]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr * arr)
#같은 위치에 있는 값들끼리를 곱한다. 
print(arr + arr)
print(1 / arr)
print(arr ** 3)

[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]
[[ 2  4  6]
 [ 8 10 12]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[  1   8  27]
 [ 64 125 216]]


In [18]:
# 같은 위치의 데이터끼리의 사칙연산이 기본값이다. 

In [19]:
arr2 = np.array([[3, 2, 1], [1, 2, 3]])
print(arr)
print(arr2)
print(arr > arr2)
# 비교 연산 (부등호, ... ) 많이 쓰게 될 것이다. 
print(arr == 3)
# == 조건에 부합하는 결과를 새로운 리스트로 반환을 하게 된다. 

[[1 2 3]
 [4 5 6]]
[[3 2 1]
 [1 2 3]]
[[False False  True]
 [ True  True  True]]
[[False False  True]
 [False False False]]


## 색인과 슬라이싱
(indexing, slicing)

In [20]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [21]:
print(arr[5])
print(arr[2:5])
#2번째 데이터 부터 5번째 데이터 전까지를 슬라이싱

5
[2 3 4]


In [22]:
arr[2:5] = 10
#list를 자른 다음에 거기에 10이라는 값을 집어넣는다. 
print(arr)
#자른 다음 대입을 했는데, 원본 데이터가 변경된다. => 파이썬의 문법과는 다름. 원본에 바로 적용되도록 설계가 되어있다. 

[ 0  1 10 10 10  5  6  7  8  9]


In [23]:
py_list = [1, 2, 3, 4, 5]
py_list[2:3].pop()
print(py_list)
#파이썬 기준으로 원본은 그대로, 변형되지 않는다. 

[1, 2, 3, 4, 5]


In [24]:
#2차원 데이터에 접근하는 방법
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)


[[1 2 3]
 [4 5 6]]


In [25]:
print(arr[1])
print(arr[1][1])
print(arr[1, 1])
# 편하게 인덱스 접근을 할 수 있게, np에서는 두번째와 세번째 표현 방법 [인덱스] [접근] / 과 [인덱스, 접근] 이 같다. 

[4 5 6]
5
5


In [26]:
#3차원 데이터에서 인덱싱 접근 방법

arr3d = np.array([[[1, 2, 3], 
          [4, 5, 6], 
          [7, 8, 9]],
         
        [[11, 12, 13],
         [14, 15, 16],
         [17, 18, 19]],

        [[11, 22, 33], 
         [44, 55, 66], 
         [77, 88, 99]]])

In [27]:
print(arr3d[2][0][1])
print(arr3d[2, 0, 1])

22
22


In [28]:
print(arr3d[:1])
#첫번째 부터 1번째 미만까지를 슬라이싱 하고 싶어요. 
print(arr3d[:1, 1:])

#슬라이싱과 인덱싱 차이 -> 차원 유지 ([대괄호가 하나 줄어든 것을 볼 수 있음: 인덱싱 접근에서])
print(arr3d[:1, 1:, 2:])
print(arr3d[0, 1:, 2:])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[4 5 6]
  [7 8 9]]]
[[[6]
  [9]]]
[[6]
 [9]]


In [29]:
arr3d[0, 1:, 2:] = 999
print(arr3d)

[[[  1   2   3]
  [  4   5 999]
  [  7   8 999]]

 [[ 11  12  13]
  [ 14  15  16]
  [ 17  18  19]]

 [[ 11  22  33]
  [ 44  55  66]
  [ 77  88  99]]]


## boolean 값으로 (데이터) 선택

데이터 비교: 각각의 아이템들의 순서에 맞게 비교를 하는 것을 확인 할 수 있었다. 

In [30]:
# 두 사람의 수학, 영어 성적을 비교하는 2차원 데이터를 만든다고 가정해보자. 

names = np.array(['hong', 'kim', 'hong', 'kim'])
data = np.array([['math', 60], ['math', 90], ['eng', 70], ['eng', 50]])
print(names)
print(data)

['hong' 'kim' 'hong' 'kim']
[['math' '60']
 ['math' '90']
 ['eng' '70']
 ['eng' '50']]


In [31]:
names == 'hong'
# np.array(['hong', 'kim', 'hong', 'kim']) 의 값과 'hong'을 비교해서 T/F로 반환해준 상태.

array([ True, False,  True, False])

In [32]:
data[[True, False, True, False]]
data[names == 'hong']

array([['math', '60'],
       ['eng', '70']], dtype='<U21')

In [33]:
print(data[names == 'hong', 1])
print(data[names == 'hong', :1])


['60' '70']
[['math']
 ['eng']]


In [34]:
print(names != 'hong')
print(~(names == 'hong'))

[False  True False  True]
[False  True False  True]


In [35]:
cond = names == 'kim'
data[cond]

array([['math', '90'],
       ['eng', '50']], dtype='<U21')

## 팬시 색인 (fancy indexing)
### 특정한 요소에 있는 인덱싱을 골라낼 때
- 행을 선택하거나
- 열을 함께 선택할 수 있음. 

In [36]:
arr = np.zeros((8, 4))
for i in range(8): 
    arr[i] = i
    # 같은 줄의 데이터에 같은 값을 넣게
print(arr)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [37]:
arr[[4, 3, 0, 5]]
# 직접적으로 [대괄호 안에 [대괄호를 쓰면서]] => 내가 원하는 행을 직접적으로 가져오게끔. 
# 순서도 내가 지정한대로 호출이 된다.

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [5., 5., 5., 5.]])

In [38]:
arr[[-3, -5, -1]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [7., 7., 7., 7.]])

In [41]:
arr = np.arange(32).reshape(8, 4)
#reshape => 내가 가진 데이터의 행렬을 바꿔줄 때 사용함. 
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [42]:
arr[[1, 5], [2, 3]]
arr[[1, 5]][:, [2, 3]]

array([[ 6,  7],
       [22, 23]])

## 배열 전치
- 배열의 축을 바꾼다.

In [43]:
arr = np.arange(15).reshape(3, 5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [44]:
print(arr.T)

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [47]:
# 행렬의 곱셈은? 
#arr * 3 # => 요소 하나하나를 곱한다. 

#행렬의 내적, 곱
print(arr @ arr.T)
print(np.dot(arr, arr.T))

[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]
[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]


## numpy 함수

In [48]:
samples = np.random.standard_normal(size=(3, 3))
print(samples)

[[-0.07763304 -1.39502583  2.67618963]
 [ 0.4185911  -0.47649566  0.08272651]
 [-0.18906933  0.5735723  -1.09820796]]


In [50]:
arr1 = np.sqrt(samples)
# 루트를 씌워줌
# nan : 숫자가 아닙니다. (python의 none과 비슷하다.)
# 여기서는 음수를 nan으로 보여줌 (=> 결측치)
print(arr1)

[[       nan        nan 1.63590636]
 [0.64698617        nan 0.28762216]
 [       nan 0.75734556        nan]]


C:\Users\박수똥\AppData\Local\Temp\ipykernel_21840\3157431161.py:1: RuntimeWarning: invalid value encountered in sqrt
  arr1 = np.sqrt(samples)


In [51]:
arr2 = np.abs(samples)
print(arr2)
#absoulute; abs = 절댓값을 취한다. 

[[0.07763304 1.39502583 2.67618963]
 [0.4185911  0.47649566 0.08272651]
 [0.18906933 0.5735723  1.09820796]]


In [52]:
np.isnan(arr1)
# 현재 내가 가진 배열 (arr1) 에 'nan'이 포함되어있나요? 

array([[ True,  True, False],
       [False,  True, False],
       [ True, False,  True]])